# Welcome to Jekyll!

# Website settings
title: "Yang Li"
description: "Yang' Lis blog,use Jekyll and github pages."
keywords: "Yang Li,Jalpc,blog,Jekyll,gh-pages"
baseurl: "https://LiYangstudio.github.io/"
url: "https://LiYangstudio.github.io/"

# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Yang Li'
  first_name: 'Li'
  last_name: 'Yang'
  email: 'LiamLeeApply@outlook.com'
  github_username: ''
  head_img: 'static/img/landing/yzh.jpg'
  mylove: ''
  desc: ''As a senior full-stack software engineer with five years at NYSE-listed Tencent Music, I contributed to the development of 'WeSing' and 'QQMusic,' apps with over 100 million daily active users, I hold international patents, including WO2023011050 and 113596516.''

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'careers'
    i18n: 'nav.careers'
    name: 'Careers'
    tpl: 'careers.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-Kingdom.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'h'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  appid: cysfY7ULn
  conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 071a17bdc10e87d669ad01b11eb29636

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#
paginate: 5
paginate_path: "blog/page/:num"
gems: [jekyll-paginate]